### ISSUE TITLE
Music Concept

### ISSUE THREAD

**Issue by janegrantham** [PuddleduckProductions/MysticForestParkRanger#10]

**Comment by Irkedibis** [comment]
Currently have a draft in Discord's #sound, will put it in a google drive link when I'm available at a computer

**Comment by Irkedibis** [comment]
Finished concept for Playtest 0 is in the drive!
https://drive.google.com/drive/folders/1EZ5NsiILK4opRDU-rmBmMtQdmnDcOBTn?usp=drive_link
