### ISSUE TITLE
Playtest Soundscape

### ISSUE THREAD

**Issue by JeremyH0451** [PuddleduckProductions/MysticForestParkRanger#11]

**Comment by Irkedibis** [comment]
Created the Slideshow file, still putting it together: https://docs.google.com/presentation/d/1tktHEY_v_gIM68QJ7mv4OPXwrqIO3EJ5c40xDCFXapk/edit?usp=sharing

**Comment by Irkedibis** [comment]
Jeremy set this up for a playtest last week (I think that was the date?), so is this task done?

**Comment by JeremyH0451** [comment]
Yeah we don't need this anymore, I'll mark it down as done
