### ISSUE TITLE
Critter Sound Effects ( Critter "Speech")

### ISSUE THREAD

**Issue by janegrantham** [PuddleduckProductions/MysticForestParkRanger#9]

**Comment by Irkedibis** [comment]
Dugong concepts are made! Waiting for design to work on interactions between the Dugong and the player before we create emotive variations of this sfx
Discord message: https://discord.com/channels/1194549610757230592/1195262323552690216/1199498234482147419

**Comment by Irkedibis** [comment]
Dugong emotive sfx are in progress, final assets appear here:
https://drive.google.com/drive/folders/1PTIRmfoTY1SMacf_fl15Hn2kM8PY3VtB?usp=drive_link

**Comment by Irkedibis** [comment]
This issue has been expanded to each individual animal, and is now outdated.

Dugong critter:
Aye Aye critter:
Mountain Animal critter:
